# Generated by Django 2.0.4 on 2018-04-18 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180411_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='new',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High'), (0, 'Low')], default=1),
        ),
        migrations.AddField(
            model_name='new',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Category'),
        ),
    ]
