# Generated by Django 2.0.4 on 2018-04-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180418_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='audio',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='new',
            name='audio_rom',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
