# Generated by Django 2.0.4 on 2018-04-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20180419_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='new',
            name='content_rom',
            field=models.TextField(),
        ),
    ]
