# Generated by Django 2.0.4 on 2018-04-19 03:05

from django.db import migrations, models
import django.utils.timezone
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20180419_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ads',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to=stdimage.utils.UploadToUUID(path='ads')),
        ),
        migrations.AddField(
            model_name='ads',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
